# Generated by Django 2.0 on 2019-03-25 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_contact_no', models.BigIntegerField()),
                ('personal_email', models.EmailField(max_length=255)),
                ('pr_street_address', models.CharField(max_length=1000)),
                ('pr_pincode', models.PositiveIntegerField()),
                ('pr_country', models.CharField(max_length=100)),
                ('pr_states', models.CharField(max_length=100)),
                ('pr_city', models.CharField(max_length=100)),
                ('cr_street_address', models.CharField(max_length=1000)),
                ('cr_pincode', models.PositiveIntegerField()),
                ('cr_country', models.CharField(max_length=100)),
                ('cr_states', models.CharField(max_length=100)),
                ('emg_name', models.CharField(max_length=255)),
                ('emg_email', models.EmailField(max_length=254)),
                ('emg_contact_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('1', 'General Manager'), ('2', 'Staff'), ('3', 'External User')], max_length=50)),
                ('company_id', models.CharField(choices=[('1', 'Global Energy Pvt Ltd'), ('2', 'Indianeye Security Pvt Ltd')], default=1, max_length=50)),
                ('bunit_id', models.CharField(choices=[('1', 'Global Belagundi')], default=1, max_length=100)),
                ('emp_code', models.CharField(max_length=50)),
                ('prefix', models.CharField(choices=[('1', 'Mr.'), ('2', 'Miss.'), ('3.', 'Mrs.'), ('4', 'Other')], max_length=20)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=500)),
                ('employment_mode', models.CharField(choices=[('1', 'Interview'), ('2', 'Direct'), ('3', 'Reference')], max_length=20)),
                ('date_of_joining', models.DateField()),
                ('reporting_manager', models.CharField(max_length=100)),
                ('dept_id', models.CharField(choices=[('1', 'Admin'), ('2', 'Store'), ('3', 'Purchase'), ('4', 'Accounts'), ('5', 'IT'), ('6', 'HR'), ('7', 'GM')], max_length=20)),
                ('role', models.CharField(choices=[('1', 'Management'), ('2', 'General Manager'), ('3', 'Manager'), ('4', 'HR'), ('5', 'Employee'), ('6', 'System Admin')], max_length=20)),
                ('job_title', models.CharField(choices=[('1', 'HR'), ('2', 'Purchase'), ('3', 'Store'), ('4', 'Admin'), ('5', 'Accounts'), ('6', 'GM'), ('7', 'IT')], max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('contact_no', models.BigIntegerField()),
                ('hod_of_dept', models.CharField(default=0, max_length=20)),
                ('added_by', models.IntegerField(null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.PositiveIntegerField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25)),
                ('position', models.CharField(choices=[('1', 'Employee'), ('2', 'Manager'), ('3', 'CEO')], max_length=25)),
                ('nationality', models.CharField(max_length=255)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=25)),
                ('salary', models.PositiveIntegerField()),
                ('deduction', models.PositiveIntegerField(default=0, null=True)),
                ('earning', models.PositiveIntegerField(default=0, null=True)),
                ('deduction_description', models.TextField(null=True)),
                ('earning_description', models.TextField(null=True)),
                ('activated', models.BooleanField(default=True)),
                ('freeze', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('wife', 'Wife'), ('child', 'Child'), ('husband', 'Husband')], max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employees')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employees'),
        ),
    ]
